import { PERMISSIONS } from './permissions';
import { ROLE_NAMES } from './roles';

const SELF_PERMISSIONS = [
  PERMISSIONS.PROFILE_READ_SELF,
  PERMISSIONS.PROFILE_UPDATE_SELF,

  PERMISSIONS.ATTENDANCE_READ_SELF,
  PERMISSIONS.ATTENDANCE_CLOCK_IN,
  PERMISSIONS.ATTENDANCE_CLOCK_OUT,

  PERMISSIONS.LEAVE_CREATE,
  PERMISSIONS.LEAVE_READ_SELF,

  PERMISSIONS.SESSION_READ_SELF,
  PERMISSIONS.SESSION_REVOKE_SELF,
] as const;

export const ROLE_PERMISSIONS = {
  [ROLE_NAMES.ADMIN]: [
    // Departments
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_UPDATE,
    PERMISSIONS.DEPARTMENT_DELETE,

    // Positions
    PERMISSIONS.POSITION_READ,
    PERMISSIONS.POSITION_CREATE,
    PERMISSIONS.POSITION_UPDATE,
    PERMISSIONS.POSITION_DELETE,

    // Employees
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,

    // Attendance
    PERMISSIONS.ATTENDANCE_READ_ALL,
    PERMISSIONS.ATTENDANCE_EDIT,
    PERMISSIONS.ATTENDANCE_QR_VIEW,

    // Leave requests
    PERMISSIONS.LEAVE_READ_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,

    ...SELF_PERMISSIONS,
  ],

  [ROLE_NAMES.MANAGER]: [
    // Departments
    PERMISSIONS.DEPARTMENT_READ,

    // Positions
    PERMISSIONS.POSITION_READ,

    // Team management
    PERMISSIONS.EMPLOYEE_READ,

    // Attendance
    PERMISSIONS.ATTENDANCE_READ_ALL,

    // Leave requests
    PERMISSIONS.LEAVE_READ_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,

    ...SELF_PERMISSIONS,
  ],

  [ROLE_NAMES.EMPLOYEE]: [...SELF_PERMISSIONS],
} as const;
